version: '3.8'

services:
   springboot-app:
    image: my-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: azerty
    depends_on:
      - mysql-db
   mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
